/**
 * This code was generated by Builder.io.
 */
'use client'
import { BUSD_ABI, BUSD_ADDRESS, getPrivateSaleABI, getPrivateSaleToken, REFERRAL_ADDRESS } from "@/utils/abis";
import detectEthereumProvider from "@metamask/detect-provider";
import React, { useEffect, useState } from "react";
import Web3 from "web3";
import {toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const PrivateSale: React.FC = () => {
const [provider,setProvider] = useState<any>(null)
const [web3,setWeb3] = useState<Web3|null>(null)
const [accounts,setAccounts] = useState([])
const [amount,setAmount] = useState('')

async function connect(){
  const ethereumProvider:any = await detectEthereumProvider();
  if(!ethereumProvider) return toast.error('Please install MetaMask!')
  const web3Instance = new Web3(ethereumProvider);
  const accounts = await ethereumProvider.request({ method: 'eth_requestAccounts' });
  setProvider(ethereumProvider);
  setAccounts(accounts);
  setWeb3(web3Instance);
}

async function enableBusd(){
  if (amount === '') return toast.error('Please enter a valid amount');
  if (+amount > 6250) return toast.error('Please enter amount less than 6250');
  if (accounts.length < 1) return  toast.error('Please connect to your wallet');
  try {
    const busdContract = new web3!.eth.Contract(BUSD_ABI, BUSD_ADDRESS); // Define BUSD_ABI and BUSD_ADDRESS appropriately
    const res = await busdContract.methods.approve(
      getPrivateSaleToken(),
      Web3.utils.toWei(+amount, 'ether')
    ).send({ from: accounts[0] });
  } catch (e) {
    alert(e);
  }
}

async function swap(){
  if (accounts.length < 1) return toast.error('Please connect to your wallet');
  const privateSaleContract = new web3!.eth.Contract(getPrivateSaleABI(), getPrivateSaleToken());
  try {
    const res = await privateSaleContract.methods.buy(
      REFERRAL_ADDRESS,
      Web3.utils.toWei(amount, 'ether')
    ).send({ from: accounts[0] })
    .on('transactionHash', function (hash) {
    
      // Handle transaction hash
    });
    toast.success('Transaction Successfull')
    // Show success modal
  } catch (e) {
    // Handle error
  }
}

  useEffect(() => {
    connect()
  }, []);

  return (
    <section className="w-full max-w-[1210px] max-md:max-w-full">
      <h2 className="mt-36 text-6xl text-center text-lime-300 leading-[80px] w-[975px] max-md:mt-10 max-md:max-w-full max-md:text-4xl max-md:leading-[64px]">
        Participate In The MONK Token <br />
        <span className="text-lime-300">Private Sale</span>
      </h2>
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-[42%] max-md:ml-0 max-md:w-full">
          <form className="flex flex-col mt-24 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 justify-between text-sm max-md:flex-wrap max-md:max-w-full">
              <label
                htmlFor="busdAmount"
                className="font-semibold text-white leading-[114%]"
              >
                Enter BUSD Amount
              </label>
              <div className="my-auto font-medium text-right text-lime-300 leading-[171%]">
                Amount: 100
              </div>
            </div>
            <div className="flex gap-5 p-5 mt-3.5 bg-white rounded-lg border border-solid shadow-sm border-zinc-950 max-md:flex-wrap max-md:max-w-full">
              <input
                type="number"
                onChange={(e)=>setAmount(e.target.value)}
                id="busdAmount"
                className="flex-auto my-auto text-base leading-6 text-neutral-600"
                placeholder="Enter BUSD Amount"
              />
              <button
                type="button"
                className="justify-center px-3 py-2 text-sm leading-6 text-center whitespace-nowrap rounded bg-lime-300 bg-opacity-50 text-teal-950"
              >
                Max
              </button>
            </div>
            <div className="flex gap-5 mt-9 text-base leading-4 text-center text-black max-md:flex-wrap">
              <button
                type="button"
                onClick={enableBusd}
                className="flex-1 justify-center px-10 py-3.5 bg-lime-300 rounded border border-black border-solid shadow-sm max-md:px-5"
              >
                Enable BUSD
              </button>
              <button
              onClick={swap}
                type="button"
                className="flex-1 justify-center px-10 py-3.5 whitespace-nowrap bg-white rounded border border-black border-solid shadow-sm max-md:px-5"
              >
                Buy
              </button>
            </div>
            <div className="justify-center px-12 py-3.5 mt-6 text-xl leading-6 text-center text-lime-300 rounded border border-dashed border-lime-300 border-opacity-40 max-md:px-5 max-md:max-w-full">
              You get: <span className="text-lime-300">15533.333</span> Monk
            </div>
            <p className="mt-3 text-xs leading-4 text-stone-300 max-md:max-w-full">
              *Web3 wallet not connected. Open this site in Trust <br /> wallet
              or Metamask dApp browser.
            </p>
          </form>
        </div>
        <div className="flex flex-col ml-5 w-[58%] max-md:ml-0 max-md:w-full">
          <div className="flex overflow-hidden relative flex-col grow items-start px-12 py-20 min-h-[679px] max-md:px-5 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d201a67a1cb5e4a49013158a78e01a97f1c58a60652d201df367945934975e40?apiKey=b4d1b9e87b084579b1e2475047caf617&"
              alt=""
              className="object-cover absolute inset-0 size-full"
            />
            <ul className="relative text-base leading-7 text-neutral-200 list-none pl-0">
              <li className="flex gap-2.5 mb-6">
                <span className="shrink-0 my-auto w-3 h-3 bg-yellow-400 rounded-full"></span>
                Minimum buy= 125 BUSD, Maximum= 6250
              </li>
              <li className="flex gap-2.5 mb-6">
                <span className="shrink-0 my-auto w-3 h-3 bg-yellow-400 rounded-full"></span>
                Total Token supply: 1,000,000,000 SiFi
              </li>
              <li className="flex gap-2.5 mb-6">
                <span className="shrink-0 my-auto w-3 h-3 bg-yellow-400 rounded-full"></span>
                Tokens allocated for Private Sale: 190,000,000 SiFi
              </li>
              <li className="flex gap-2.5">
                <span className="shrink-0 my-auto w-3 h-3 bg-yellow-400 rounded-full"></span>
                Note: Earn referral rewards in BUSD by inviting your friends to
                buy SiFi tokens.
              </li>
            </ul>
            <button className="flex relative gap-2 justify-center px-5 py-3 mt-4 ml-7 text-sm leading-4 bg-white border border-solid border-slate-800 rounded-[999px] text-slate-800 max-md:ml-2.5">
              Click to view Rates
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e8819bfb2b02b753ae5e23840aafd27affb08928997fd5a23fb909622e9ad524?apiKey=b4d1b9e87b084579b1e2475047caf617&"
                alt=""
                className="shrink-0 my-auto aspect-[0.63] w-[5px]"
              />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default PrivateSale;
